name: Deploy Angular App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Latest Node
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'npm'

      - run: npm install -g @angular/cli
      - run: npm install
      - run: npm run build

      - name: Setup 404 Routing
        run: cd dist/programiranje-korisnickih-interfejsa-2025/browser && cp index.html 404.html

      - name: Deploy to Branch
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: dist/programiranje-korisnickih-interfejsa-2025/browser